language: c
matrix:
    include:
        - compiler: gcc
            os: linux
        - compiler: clang
            os: osx

before_install:

script:
    make

branches:
    only:
        -master

osx_image: xcode7.3
