language: c
os:
    - linux
    - osx

matrix:
    include:
        - compiler: gcc
            os: linux
        - compiler: clang
            os: osx

before_install:
    #installing dependencies for osx
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcode-select –install; fi
	- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ruby -e “$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)”; fi
	- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew doctor; fi
	- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install caskroom/cask/brew-cask; fi
	#installing dependencies for linux
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libglew-dev
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libglfw-dev

script:
    - cd src
    - make
    - ./build/bin/main 

branches:
    only:
        -master
